# --enable-features=WaylandLinuxDrmSyncobj,WaylandWindowDecorations,WaylandPerSurfaceScale,WaylandUiScale
# --enable-features=WaylandWindowDecorations,WaylandPerSurfaceScale,WaylandUiScale
# --disable-features=WaylandWpColorManagerV1
--ozone-platform-hint=wayland
