# vim:fileencoding=utf-8:foldmethod=marker

# Usability
confirm_os_window_close 0
window_padding_width 4
cursor_shape beam

## Fix issue with ssh & backspace
term xterm-256color

# Keymap
map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+c copy_or_interrupt
map ctrl+alt+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+v paste_from_clipboard

# Tabs
tab_bar_min_tabs            2
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         round
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''

# Appearance
font_family JetBrainsMono Nerd Font
font_size 12

## Animate cursor
cursor_trail 3
cursor_trail_decay 0.1 0.4

map shift+enter send_text all \e\r

allow_remote_control socket-only
listen_on unix:/tmp/kitty
# map ctrl+v launch --type=background --allow-remote-control --keep-focus ~/.local/bin/clip2path

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
