#!/bin/sh
BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

echo "SOURIS"
explain "Suppresion de l'accélération"
  tell cp -f $BASEDIR/files/mousespeed $HOME/.config/mousespeed
  tell chmod +x $HOME/.config/mousespeed
  cat /dev/null > $HOME/.config/autostart/mousespeed.desktop
  cat > $HOME/.config/autostart/mousespeed.desktop <<- EOM
[Desktop Entry]
Encoding=UTF-8
Version=1.0.0
Type=Application
Name=Mouse Speed
Comment=
Exec=$HOME/.config/mousespeed
OnlyShowIn=XFCE;
StartupNotify=false
Terminal=false
Hidden=false
EOM
  tell chmod 644 $HOME/.config/autostart/mousespeed.desktop

success "Souris ralentie avec succès"
