#!/bin/sh

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

explain "Installation de RVM"
  command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
  \curl -sSL https://get.rvm.io | bash -s stable
  source $HOME/.rvm/scripts/rvm

explain "Installation de ruby"
  tell rvm install 2.2

explain "Installation de bundler"
  tell gem install bundler
