#!/bin/sh

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

explain "Installation de RVM"
  tell sudo apt-get install -y curl
  gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  \curl -sSL https://get.rvm.io | bash -s stable
  source $HOME/.rvm/scripts/rvm

explain "Installation de ruby"
  tell rvm install 2.2

explain "Installation de bundler"
  tell gem install bundler
