#!/bin/sh

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

explain "Requirements"
  tell sudo apt-get install -y exuberant-ctags cmake libevent-dev libncurses5-dev

explain "Install de Tmux"
  tell cd ~
  tell wget https://github.com/tmux/tmux/releases/download/2.1/tmux-2.1.tar.gz
  tell tar xvf tmux-2.1.tar.gz
  tell cd tmux-2.1
  tell ./configure
  tell make
  tell sudo make install
  tell cd ..
  tell rm -rf tmux-2.1.tar.gz
  tell rm -rf tmux-2.1

explain "Install de tmux plugin manager"
  tell git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

explain "Copie de la configuration"
  tell cp $(dirname $BASEDIR)/.tmux.conf $HOME/.tmux.conf
