#!/bin/sh

# Fonts
sudo apt-get install gnome-font-viewer

# Arc-theme
wget http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_15.10/Release.key
sudo apt-key add - < Release.key
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_15.10/ /' >> /etc/apt/sources.list.d/arc-theme.list"
sudo apt-get update
sudo apt-get install arc-theme

# Flat icons
sudo add-apt-repository ppa:noobslab/icons
sudo apt-get update
sudo apt-get install ultra-flat-icons

# Moka icons
sudo add-apt-repository ppa:moka/stable
sudo apt-get update
sudo apt-get install moka-icon-theme

# Arc-theme
wget http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_15.04/Release.key
sudo apt-key add - < Release.key
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_15.04/ /' >> /etc/apt/sources.list.d/arc-theme.list"
sudo apt-get update
sudo apt-get install arc-theme

# Terminal 
BASEDIR=$(dirname $0)
cp $BASEDIR/files/terminalrc $HOME/.config/xfce4/terminal/terminalrc/terminalrc

# No screen reader
sudo apt-get remove gnome-orca
killall orca

# Alt + Click disable (pour la multi selection sur Intellij)
xfconf-query -c xfwm4 -p /general/easy_click -s none