#!/bin/sh

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

explain "Installation de gnome-font-viewer"
  tell sudo apt-get install gnome-font-viewer

explain "Installation d'arc-theme"
  tell wget http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_15.10/Release.key
  sudo apt-key add - < Release.key
  sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_15.10/ /' >> /etc/apt/sources.list.d/arc-theme.list"
  tell sudo apt-get update
  tell sudo apt-get install arc-theme

explain "Installation de flat icons"
  tell sudo add-apt-repository ppa:noobslab/icons
  tell sudo apt-get update
  tell sudo apt-get install ultra-flat-icons

explain "Installation du theme pour le terminal"
  cp $BASEDIR/files/terminalrc $HOME/.config/xfce4/terminal/terminalrc/terminalrc

explain "Désactivation du Alt+Clic"
  tell xfconf-query -c xfwm4 -p /general/easy_click -s none

explain "Installation de compton pour la compo des fenetre"
  tell sudo apt-add-repository ppa:richardgv/compton
  tell sudo apt-get update
  tell sudo apt-get install compton
  tell cp $(dirname $BASEDIR)/.compton.conf $HOME/.compton.conf

explain "Installation du gestionnaire du moniteur système"
  tell sudo apt-get install gnome-system-monitor

explain "Mise en place de la configuration personnalisée"
  cp $BASEDIR/files/xfce4-keyboard-shortcuts.xml $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
  cp $BASEDIR/files/xfce4-panel.xml $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
